spring:
  datasource:
    url: "jdbc:mysql://dev-aurora-mysql.cvytkk0k4stw.ap-northeast-2.rds.amazonaws.com:3306/cetaphil-event"
    username: "cetaphil-event"
    password: "Vpsxkzmf^&*12"
    tomcat:
      max-active: 2
      max-idle: 2
  jpa:  
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false   
    
  session:
    store-type: jdbc
    jdbc:
      initializer:
        enabled: true
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      
  thymeleaf:
    mode: LEGACYHTML5
      
server: 
  error:
    whitelabel:
      enabled: false
      
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.cetaphilevent: DEBUG
    
query:
  security:
    users: select email,password,user_id from user where email =? 
    roles: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?


---
spring:
  profiles: development
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 2
      max-idle: 2
            
---
spring:
  profiles: production
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 10
      max-idle: 10      
      
logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.cetaphilevent: ERROR
  
  
