spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 4
      max-idle: 4
      initial-size: 4
  
  jpa:  
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

  session:
    store-type: jdbc
    jdbc:
      initializer:
        enabled: true
      schema: classpath:org/springframework/session/jdbc/schema-@@plaform@@.sql

  thymeleaf:
    mode: LEGACYHTML5

server: 
  error:
    whitelabel:
      enabled: false
      
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
  
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.babience: DEBUG

---
spring:
  profiles: development
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 5
      max-idle: 5
      initial-size: 5
---
spring:
  profiles: production
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 10
      max-idle: 10
      initial-size: 10
    
logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.babience: INFO
  
  

