// <auto-generated />
namespace Finnq.Promotion.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createtmapevententry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtmapevententry));
        
        string IMigrationMetadata.Id
        {
            get { return "201709270538042_create-tmap-event-entry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
