// <auto-generated />
namespace Finnq.Promotion.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createtrouletteevent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtrouletteevent));
        
        string IMigrationMetadata.Id
        {
            get { return "201711080037537_create-t-roulette-event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
